### ISSUE TITLE
Cannot open file models/obj-f16.obj

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-039-kingdom#1]
Pri pokretanju se ispisuje poruka "Cannot open file models/obj-f16.obj"

**Comment by ivan-cukic-matf** [comment]
(izbacite iz .gitignore .obj fajlove i dodajte obj fajl u repo)

**Comment by NikolaR92** [comment]
Ubaceni su sad objekti. Trebalo bi sad radi.
